import { THEME } from "./reportsConfig";
import type { RecentReport, ScheduledReport } from "./reportsConfig";
import { AgentDot } from "../PrimeChatV2/AgentDot";
import { Reveal } from "../PrimeChatV2/Reveal";
import type { AgentName } from "../PrimeChatV2/agentConfig";

interface ReportsListProps {
  reports: RecentReport[];
}

export function ReportsList({ reports }: ReportsListProps) {
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
      {reports.map((r, i) => (
        <Reveal key={r.name} delay={100 + i * 60}>
          <div style={{
            display: "flex", alignItems: "center", gap: 16, padding: "16px 20px",
            background: THEME.surface, border: `1px solid ${THEME.border}`, borderRadius: 14,
            cursor: "pointer", transition: "all 0.15s",
            boxShadow: `0 2px 12px ${r.color}04`,
          }}
          onMouseEnter={(e: React.MouseEvent<HTMLDivElement>) => { e.currentTarget.style.borderColor = `${r.color}33`; e.currentTarget.style.background = "#1a2844"; }}
          onMouseLeave={(e: React.MouseEvent<HTMLDivElement>) => { e.currentTarget.style.borderColor = THEME.border; e.currentTarget.style.background = THEME.surface; }}
          >
            <div style={{ width: 40, height: 40, borderRadius: 12, background: `${r.color}10`, display: "flex", alignItems: "center", justifyContent: "center" }}>
              <AgentDot agent={r.agent as AgentName} size={28} />
            </div>
            <div style={{ flex: 1 }}>
              <div style={{ fontSize: 14, fontWeight: 600, color: THEME.text }}>{r.name}</div>
              <div style={{ fontSize: 11, color: THEME.textDim, marginTop: 2 }}>Generated by {r.agent} \u2022 {r.date}</div>
            </div>
            <div style={{ textAlign: "right" }}>
              <span style={{ fontSize: 10.5, color: THEME.textDim, padding: "3px 10px", borderRadius: 6, background: THEME.bg, border: `1px solid ${THEME.border}` }}>{r.format}</span>
              <div style={{ fontSize: 10, color: THEME.textDim, marginTop: 4 }}>{r.size}</div>
            </div>
            <div style={{ display: "flex", gap: 6 }}>
              <button style={{ padding: "6px 14px", borderRadius: 8, fontSize: 11, fontWeight: 600, background: `${r.color}12`, border: `1px solid ${r.color}28`, color: r.color, cursor: "pointer" }}>{"\u2B07"} Download</button>
              <button style={{ padding: "6px 14px", borderRadius: 8, fontSize: 11, fontWeight: 600, background: THEME.surfaceLight, border: `1px solid ${THEME.border}`, color: THEME.textMuted, cursor: "pointer" }}>{"\uD83D\uDCE7"} Send</button>
            </div>
          </div>
        </Reveal>
      ))}
    </div>
  );
}

interface ScheduledListProps {
  reports: ScheduledReport[];
}

export function ScheduledList({ reports }: ScheduledListProps) {
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
      {reports.map((s, i) => (
        <Reveal key={s.name} delay={100 + i * 60}>
          <div style={{
            display: "flex", alignItems: "center", gap: 16, padding: "18px 22px",
            background: THEME.surface, border: `1px solid ${THEME.border}`, borderRadius: 14,
            boxShadow: `0 2px 12px ${s.color}04`,
          }}>
            <AgentDot agent={s.agent as AgentName} size={36} />
            <div style={{ flex: 1 }}>
              <div style={{ fontSize: 14, fontWeight: 600, color: THEME.text }}>{s.name}</div>
              <div style={{ fontSize: 11, color: THEME.textDim, marginTop: 2 }}>
                {s.freq} \u2022 Next: <span style={{ color: THEME.text, fontWeight: 600 }}>{s.next}</span>
              </div>
            </div>
            <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
              <span style={{
                fontSize: 10.5, fontWeight: 700, padding: "4px 12px", borderRadius: 8,
                background: s.active ? "rgba(52,211,153,0.08)" : "rgba(248,113,113,0.08)",
                color: s.active ? "#34d399" : "#f87171",
                border: `1px solid ${s.active ? "#34d399" : "#f87171"}22`,
              }}>{s.active ? "Active" : "Paused"}</span>
              <div style={{
                width: 40, height: 22, borderRadius: 11, cursor: "pointer",
                background: s.active ? "#34d399" : THEME.border,
                position: "relative", transition: "background 0.2s",
              }}>
                <div style={{
                  width: 18, height: 18, borderRadius: "50%", background: "#fff",
                  position: "absolute", top: 2, left: s.active ? 20 : 2, transition: "left 0.2s",
                }} />
              </div>
            </div>
          </div>
        </Reveal>
      ))}

      <Reveal delay={100 + reports.length * 60}>
        <div style={{
          display: "flex", alignItems: "center", justifyContent: "center", gap: 10,
          padding: "20px", borderRadius: 14, border: `2px dashed ${THEME.border}`,
          cursor: "pointer", transition: "all 0.15s",
        }}
        onMouseEnter={(e: React.MouseEvent<HTMLDivElement>) => { e.currentTarget.style.borderColor = THEME.accent; e.currentTarget.style.background = THEME.accentGlow; }}
        onMouseLeave={(e: React.MouseEvent<HTMLDivElement>) => { e.currentTarget.style.borderColor = THEME.border; e.currentTarget.style.background = "transparent"; }}
        >
          <span style={{ fontSize: 20, color: THEME.accent }}>+</span>
          <span style={{ fontSize: 13, fontWeight: 600, color: THEME.accent }}>Schedule a New Report</span>
        </div>
      </Reveal>
    </div>
  );
}
