import { LegalLayout, H2, P } from "./LegalLayout";

export default function DisclaimerPage() {
  return (
    <LegalLayout title="Disclaimer" updated="March 22, 2026">
      <H2>Not Financial Advice</H2>
      <P>XspensesAI and all of its AI agents — including Prime (Advisor), Byte (Smart Import), Tag (Categorizer), Crystal (Analytics), Goalie (Goals Coach), and Ledger (Tax Organizer) — are software tools designed to help you organize and understand your financial data. They are not licensed financial advisors, certified public accountants, tax professionals, investment advisors, or legal counsel.</P>
      <P>Nothing provided by the Service constitutes financial advice, tax advice, legal advice, or investment advice. All categorizations, insights, summaries, recommendations, and analyses generated by our AI agents are informational and organizational in nature. They should not be relied upon as a substitute for professional advice from qualified professionals.</P>

      <H2>Tax Categorization</H2>
      <P>The tax categorization features provided by Tag and Ledger are suggested categorizations only. These suggestions are generated by machine learning algorithms based on transaction patterns and may not accurately reflect the tax treatment of your specific transactions under Canadian Revenue Agency (CRA) rules or other tax authorities. You must verify all tax-related categorizations with your accountant or tax professional before filing any tax returns or making tax-related decisions.</P>

      <H2>Xspense Score</H2>
      <P>The Xspense Score is an internal engagement and organizational metric calculated by XspensesAI. It is NOT a credit score, credit rating, or financial health certification. The Xspense Score is not used by any financial institution, credit bureau, or third party. It is designed to gamify and encourage good financial organization habits within the app. Changes to your Xspense Score have no bearing on your actual creditworthiness, borrowing capacity, or financial health.</P>

      <H2>AI-Generated Content</H2>
      <P>All text, summaries, insights, and recommendations generated by our AI agents are produced by large language models and machine learning algorithms. While we strive for accuracy, AI-generated content may contain errors, omissions, or inaccuracies. Past financial analysis and trend detection do not predict future results. Users should independently verify any information provided by the Service before acting on it.</P>

      <H2>User Responsibility</H2>
      <P>You are solely responsible for your financial decisions. XspensesAI provides tools to help you organize and understand your finances, but the ultimate responsibility for financial decisions rests with you. If you are in doubt about any financial matter, we strongly recommend consulting a Certified Public Accountant (CPA), Chartered Professional Accountant (CPA), licensed financial advisor, or qualified tax professional.</P>

      <H2>OCR and Data Accuracy</H2>
      <P>Our optical character recognition (OCR) system extracts text from uploaded financial documents with high but not perfect accuracy. Extracted transaction data may contain errors due to document quality, formatting variations, or OCR limitations. Users should review extracted transactions for accuracy, particularly for tax-related purposes.</P>

      <H2>Contact</H2>
      <P>For questions about this disclaimer, contact us at legal@xspensesai.com.</P>
    </LegalLayout>
  );
}
