// FINAL: Do not edit this file unless you are Darrell Warner or have explicit permission.
import { useState, useEffect, useRef } from "react";
import { 
  Home, 
  BarChart3, 
  Settings, 
  User, 
  CreditCard, 
  TrendingUp, 
  Target, 
  Brain, 
  MessageSquare, 
  FileText, 
  Upload, 
  Receipt, 
  Calculator, 
  Building2, 
  Zap, 
  PieChart, 
  Calendar, 
  Bell, 
  Crown, 
  Award, 
  Play, 
  Mic, 
  Music, 
  Headphones, 
  BookOpen, 
  Heart,
  Bot,
  Menu,
  ChevronLeft,
  ChevronRight
} from 'lucide-react';
import { Link, NavLink, useLocation } from "react-router-dom";
import { useUser } from "../../contexts/UserContext";

export default function Sidebar({ isMobileOpen, setIsMobileOpen }: { isMobileOpen: boolean; setIsMobileOpen: (open: boolean) => void }) {
  const [isCollapsed, setIsCollapsed] = useState(false);
  const location = useLocation();
  const sidebarRef = useRef<HTMLDivElement>(null);
  const user = useUser();

  // Preserve sidebar scroll position on route change
  useEffect(() => {
    const sidebar = sidebarRef.current;
    if (sidebar) {
      const savedScrollTop = sessionStorage.getItem('sidebarScrollTop');
      if (savedScrollTop) {
        // Restore scroll position immediately
        sidebar.scrollTop = parseInt(savedScrollTop);
        
        // Also restore after a delay to ensure it sticks
        setTimeout(() => {
          sidebar.scrollTop = parseInt(savedScrollTop);
        }, 100);
        
        // And again after a longer delay
        setTimeout(() => {
          sidebar.scrollTop = parseInt(savedScrollTop);
        }, 500);
      }
    }
  }, [location.pathname]);

  // Save sidebar scroll position before route change
  useEffect(() => {
    const sidebar = sidebarRef.current;
    if (sidebar) {
      const handleScroll = () => {
        sessionStorage.setItem('sidebarScrollTop', sidebar.scrollTop.toString());
      };
      
      sidebar.addEventListener('scroll', handleScroll);
      return () => sidebar.removeEventListener('scroll', handleScroll);
    }
  }, []);

  // Clear scroll position when leaving dashboard
  useEffect(() => {
    if (location.pathname.startsWith('/dashboard')) {
      sessionStorage.removeItem('sidebarScrollPosition');
    }
  }, [location.pathname]);

  // Force scroll restoration on every render for dashboard routes
  useEffect(() => {
    if (location.pathname.startsWith('/dashboard')) {
      const savedPosition = sessionStorage.getItem('sidebarScrollPosition');
      if (savedPosition) {
        setTimeout(() => {
          if (sidebarRef.current) {
            sidebarRef.current.scrollTop = parseInt(savedPosition);
          }
        }, 100);
      }
    }
  }, [location.pathname]);

  const toggleSidebar = () => {
    setIsCollapsed(!isCollapsed);
  };

  return (
    <aside className="h-full w-full bg-[#0b0f2a] text-white flex flex-col" ref={sidebarRef}>
      <div className="h-full flex flex-col">
        {/* Scrollable Container */}
        <div className="flex-1 overflow-y-auto [scrollbar-gutter:stable]">
          {/* Header with Logo - Professional Design */}
          <div className="sticky top-0 border-b border-white/10 p-6 backdrop-blur-md">
          <div className="flex items-center justify-between">
                         {!isCollapsed && (
               <div className="flex items-center gap-4 flex-1">
                 <span className="rounded-full bg-gradient-to-br from-yellow-400 to-orange-500 p-4 shadow-xl">
                   <Crown className="text-white" size={36} />
        </span>
        <div>
                   <span className="font-bold text-2xl leading-tight tracking-tight text-white">XspensesAI</span>
                 </div>
               </div>
             )}
                         {isCollapsed && (
               <div className="flex items-center justify-center flex-1">
                 <span className="rounded-full bg-gradient-to-br from-yellow-400 to-orange-500 p-3 shadow-xl">
                   <Crown className="text-white" size={32} />
                 </span>
               </div>
             )}
                         <div className="flex items-center gap-3">
               {/* Collapse Toggle Button */}
               <button 
                 onClick={toggleSidebar}
                 className="p-2 text-white/70 hover:text-white hover:bg-white/10 rounded-xl transition-all duration-300"
                 style={{ minHeight: '44px', minWidth: '44px' }}
               >
                 {isCollapsed ? <ChevronRight size={22} /> : <ChevronLeft size={22} />}
               </button>
             </div>
          </div>
        </div>

                 {/* Navigation with Professional Scrolling - Optimized Height */}
         <nav className="flex-1 overflow-y-auto px-6 py-6 pb-24" style={{ height: 'calc(100vh - 160px)' }}>
          {/* Main Dashboard */}
          <ul className="space-y-2 mb-6">
            <li>
              <NavLink 
                to="/dashboard" 
                className={({ isActive }) => 
                  `flex items-center gap-3 py-3 px-3 rounded-lg transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                    isActive ? 'bg-white/20 border-l-4 border-purple-400' : ''
                  }`
                }
                style={{ minHeight: '44px' }}
              >
                <BarChart3 size={20} className="flex-shrink-0" />
                {!isCollapsed && <span className="font-medium">Main Dashboard</span>}
              </NavLink>
            </li>
          </ul>

          {/* Personal Finance AI */}
          {!isCollapsed && (
            <div className="text-xs uppercase tracking-wider text-white/50 mt-4 mb-6 font-bold">
              Personal Finance AI
            </div>
          )}
          <ul className="space-y-2 mb-10">
            <li>
              <NavLink 
                to="/dashboard/smart-import-ai" 
                className={({ isActive }) => 
                  `flex items-center gap-3 py-3 px-3 rounded-lg transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                    isActive ? 'bg-white/20 border-l-4 border-purple-400' : ''
                  }`
                }
                style={{ minHeight: '44px' }}
              >
                <Upload size={20} className="flex-shrink-0" />
                {!isCollapsed && <span className="font-medium">Smart Import AI</span>}
              </NavLink>
            </li>
            <li>
              <NavLink 
                to="/dashboard/ai-financial-assistant" 
                className={({ isActive }) => 
                  `flex items-center gap-3 py-3 px-3 rounded-lg transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                    isActive ? 'bg-white/20 border-l-4 border-purple-400' : ''
                  }`
                }
                style={{ minHeight: '44px' }}
              >
                <Bot size={20} className="flex-shrink-0" />
                {!isCollapsed && <span className="font-medium">AI Financial Assistant</span>}
              </NavLink>
            </li>
            <li>
              <NavLink 
                to="/dashboard/financial-therapist" 
                className={({ isActive }) => 
                  `flex items-center gap-3 py-3 px-3 rounded-lg transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                    isActive ? 'bg-white/20 border-l-4 border-purple-400' : ''
                  }`
                }
                style={{ minHeight: '44px' }}
              >
                <Heart size={20} className="flex-shrink-0" />
                {!isCollapsed && <span className="font-medium">AI Financial Therapist</span>}
              </NavLink>
            </li>

            <li>
              <NavLink 
                to="/dashboard/goal-concierge" 
                className={({ isActive }) => 
                  `flex items-center gap-3 py-3 px-3 rounded-lg transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                    isActive ? 'bg-white/20 border-l-4 border-purple-400' : ''
                  }`
                }
                style={{ minHeight: '44px' }}
              >
                <Target size={20} className="flex-shrink-0" />
                {!isCollapsed && <span className="font-medium">AI Goal Concierge</span>}
              </NavLink>
            </li>
            <li>
              <NavLink 
                to="/dashboard/spending-predictions" 
                className={({ isActive }) => 
                  `flex items-center gap-3 py-3 px-3 rounded-lg transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                    isActive ? 'bg-white/20 border-l-4 border-purple-400' : ''
                  }`
                }
                style={{ minHeight: '44px' }}
              >
                <Brain size={20} className="flex-shrink-0" />
                {!isCollapsed && <span className="font-medium">Spending Predictions</span>}
              </NavLink>
            </li>
            <li>
              <NavLink 
                to="/dashboard/ai-categorization" 
                className={({ isActive }) => 
                  `flex items-center gap-3 py-3 px-3 rounded-lg transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                    isActive ? 'bg-white/20 border-l-4 border-purple-400' : ''
                  }`
                }
                style={{ minHeight: '44px' }}
              >
                <Brain size={20} className="flex-shrink-0" />
                {!isCollapsed && <span className="font-medium">AI Categorization</span>}
              </NavLink>
            </li>
        </ul>

            {/* 💳 Expense & Planning Tools */}
          {!isCollapsed && (
            <div className="text-xs uppercase tracking-wider text-white/40 mt-6 mb-4 font-semibold">
                💳 Expense & Planning Tools
            </div>
          )}
          <ul className="space-y-1 mb-8">
            <li>
              <NavLink 
                to="/dashboard/bill-reminders" 
                className={({ isActive }) => 
                  `flex items-center gap-3 py-3 px-3 rounded-lg transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                    isActive ? 'bg-white/20 border-l-4 border-purple-400' : ''
                  }`
                }
                style={{ minHeight: '44px' }}
              >
                <Bell size={20} className="flex-shrink-0" />
                {!isCollapsed && <span className="font-medium">Bill Reminder System</span>}
              </NavLink>
            </li>
            <li>
              <NavLink 
                to="/dashboard/debt-payoff-planner" 
                className={({ isActive }) => 
                  `flex items-center gap-3 py-3 px-3 rounded-lg transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                    isActive ? 'bg-white/20 border-l-4 border-purple-400' : ''
                  }`
                }
                style={{ minHeight: '44px' }}
              >
                <TrendingUp size={20} className="flex-shrink-0" />
                {!isCollapsed && <span className="font-medium">Debt Payoff Planner</span>}
              </NavLink>
            </li>
              <li>
                <NavLink 
                  to="/dashboard/financial-freedom" 
                  className={({ isActive }) => 
                    `flex items-center gap-3 py-3 px-3 rounded-lg transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                      isActive ? 'bg-white/20 border-l-4 border-purple-400' : ''
                    }`
                  }
                  style={{ minHeight: '44px' }}
                >
                  <Crown size={20} className="flex-shrink-0" />
                  {!isCollapsed && <span className="font-medium">AI Financial Freedom</span>}
                </NavLink>
              </li>
        </ul>

        {/* Audio Entertainment */}
          {!isCollapsed && (
            <div className="text-xs uppercase tracking-wider text-white/40 mt-6 mb-4 font-semibold">
              Audio Entertainment
            </div>
          )}
          <ul className="space-y-1 mb-8">
            <li>
              <NavLink 
                to="/dashboard/personal-podcast" 
                className={({ isActive }) => 
                  `flex items-center gap-3 py-3 px-3 rounded-lg transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                    isActive ? 'bg-white/20 border-l-4 border-purple-400' : ''
                  }`
                }
                style={{ minHeight: '44px' }}
              >
                <Headphones size={20} className="flex-shrink-0" />
                {!isCollapsed && <span className="font-medium">Personal Podcast</span>}
              </NavLink>
            </li>
            <li>
              <NavLink 
                to="/dashboard/spotify-integration" 
                className={({ isActive }) => 
                  `flex items-center gap-3 py-3 px-3 rounded-lg transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                    isActive ? 'bg-white/20 border-l-4 border-purple-400' : ''
                  }`
                }
                style={{ minHeight: '44px' }}
              >
                <Music size={20} className="flex-shrink-0" />
                {!isCollapsed && <span className="font-medium">Spotify Integration</span>}
              </NavLink>
            </li>
            <li>
              <NavLink 
                to="/dashboard/wellness-studio" 
                className={({ isActive }) => 
                  `flex items-center gap-3 py-3 px-3 rounded-lg transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                    isActive ? 'bg-white/20 border-l-4 border-purple-400' : ''
                  }`
                }
                style={{ minHeight: '44px' }}
              >
                <Heart size={20} className="flex-shrink-0" />
                {!isCollapsed && <span className="font-medium">Financial Wellness Studio</span>}
              </NavLink>
            </li>
        </ul>

        {/* Tax Assistant, Business Intelligence, Smart Automation */}
          {!isCollapsed && (
            <div className="text-xs uppercase tracking-wider text-white/40 mt-6 mb-4 font-semibold">
              Tax Assistant, Business Intelligence, Smart Automation
            </div>
          )}
          <ul className="space-y-1 mb-8">
            <li>
              <NavLink 
                to="/dashboard/tax-assistant" 
                className={({ isActive }) => 
                  `flex items-center gap-3 py-3 px-3 rounded-lg transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                    isActive ? 'bg-white/20 border-l-4 border-purple-400' : ''
                  }`
                }
                style={{ minHeight: '44px' }}
              >
                <Calculator size={20} className="flex-shrink-0" />
                {!isCollapsed && <span className="font-medium">Tax Assistant</span>}
              </NavLink>
            </li>
            <li>
              <NavLink 
                to="/dashboard/business-intelligence" 
                className={({ isActive }) => 
                  `flex items-center gap-3 py-3 px-3 rounded-lg transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                    isActive ? 'bg-white/20 border-l-4 border-purple-400' : ''
                  }`
                }
                style={{ minHeight: '44px' }}
              >
                <BarChart3 size={20} className="flex-shrink-0" />
                {!isCollapsed && <span className="font-medium">Business Intelligence</span>}
              </NavLink>
            </li>
            <li>
              <NavLink 
                to="/dashboard/smart-automation" 
                className={({ isActive }) => 
                  `flex items-center gap-3 py-3 px-3 rounded-lg transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                    isActive ? 'bg-white/20 border-l-4 border-purple-400' : ''
                  }`
                }
                style={{ minHeight: '44px' }}
              >
                <Zap size={20} className="flex-shrink-0" />
                {!isCollapsed && <span className="font-medium">Smart Automation</span>}
              </NavLink>
            </li>
        </ul>

        {/* Tools */}
          {!isCollapsed && (
            <div className="text-xs uppercase tracking-wider text-white/40 mt-6 mb-4 font-semibold">
              Tools
            </div>
          )}
          <ul className="space-y-1 mb-8">
            <li>
              <NavLink 
                to="/dashboard/analytics" 
                className={({ isActive }) => 
                  `flex items-center gap-3 py-3 px-3 rounded-lg transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                    isActive ? 'bg-white/20 border-l-4 border-purple-400' : ''
                  }`
                }
                style={{ minHeight: '44px' }}
              >
                <BarChart3 size={20} className="flex-shrink-0" />
                {!isCollapsed && <span className="font-medium">Analytics</span>}
              </NavLink>
            </li>
            <li>
              <NavLink 
                to="/dashboard/settings" 
                className={({ isActive }) => 
                  `flex items-center gap-3 py-3 px-3 rounded-lg transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                    isActive ? 'bg-white/20 border-l-4 border-purple-400' : ''
                  }`
                }
                style={{ minHeight: '44px' }}
              >
                <Settings size={20} className="flex-shrink-0" />
                {!isCollapsed && <span className="font-medium">Settings</span>}
              </NavLink>
            </li>
            <li>
              <NavLink 
                to="/dashboard/reports" 
                className={({ isActive }) => 
                  `flex items-center gap-3 py-3 px-3 rounded-lg transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                    isActive ? 'bg-white/20 border-l-4 border-purple-400' : ''
                  }`
                }
                style={{ minHeight: '44px' }}
              >
                <FileText size={20} className="flex-shrink-0" />
                {!isCollapsed && <span className="font-medium">Reports</span>}
              </NavLink>
            </li>
        </ul>
      </nav>

        </div>
      </div> {/* end of scrollable nav */}
      </div> {/* closes: h-full flex flex-col */}

      {/* profile footer at the very bottom */}
      <div className="border-t border-white/10 px-4 py-4 mt-auto w-full box-border">
        {/* User Block - Compact Professional Design */}
        {!isCollapsed && (
          <div className="p-4 pr-6 bg-blue-900 w-full box-border">
            <div className="text-sm">
              <div className="font-semibold">{user.name}</div>
              <div className="text-xs text-gray-300">{user.plan}</div>
            </div>
            <div className="mt-2 bg-orange-500 rounded-full text-xs text-white px-3 py-1 inline-block">
              Level 8 Money Master
            </div>
          </div>
        )}
      </div>
    </aside>
  );
}
