// FINAL: Do not edit this file unless you are Darrell Warner or have explicit permission.
import React, { useState, useRef, useEffect } from 'react';
import { NavLink, useLocation } from 'react-router-dom';
import { 
  Home, 
  BarChart3, 
  Upload, 
  Brain, 
  Heart, 
  Target, 
  TrendingUp, 
  Mic, 
  Music, 
  Briefcase, 
  Calculator, 
  Zap, 
  FileText, 
  Settings, 
  User, 
  LogOut,
  ChevronLeft,
  ChevronRight,
  Menu,
  X,
  Bot,
  Bell,
  CreditCard,
  Award,
  Building2,
  Headphones,
  Banknote,
  Star,
  Sparkles
} from 'lucide-react';
import Logo from '../common/Logo';
import { motion, AnimatePresence } from 'framer-motion';
import { useUser } from "../../contexts/UserContext";

export default function Sidebar({ isMobileOpen, setIsMobileOpen }: { isMobileOpen: boolean; setIsMobileOpen: (open: boolean) => void }) {
  const [isCollapsed, setIsCollapsed] = useState(false);
  const [shouldShowLabels, setShouldShowLabels] = useState(true);
  const sidebarRef = useRef<HTMLDivElement>(null);
  const location = useLocation();
  const user = useUser();

  // CORRECT LOGIC: Only show sidebar on dashboard routes
  if (!location.pathname.startsWith('/dashboard')) {
    return null; // Hide sidebar on ALL non-dashboard routes
  }
  
  // Show sidebar ONLY on dashboard routes
  // Continue with sidebar rendering

  // Preserve sidebar scroll position on route change
  useEffect(() => {
    const sidebar = sidebarRef.current;
    if (sidebar) {
      const savedScrollTop = sessionStorage.getItem('sidebarScrollTop');
      if (savedScrollTop) {
        // Restore scroll position immediately
        sidebar.scrollTop = parseInt(savedScrollTop);
        
        // Also restore after a delay to ensure it sticks
        setTimeout(() => {
          sidebar.scrollTop = parseInt(savedScrollTop);
        }, 100);
        
        // And again after a longer delay
        setTimeout(() => {
          sidebar.scrollTop = parseInt(savedScrollTop);
        }, 500);
      }
    }
  }, [location.pathname]);

  // Save sidebar scroll position before route change
  useEffect(() => {
    const sidebar = sidebarRef.current;
    if (sidebar) {
      const handleScroll = () => {
        sessionStorage.setItem('sidebarScrollTop', sidebar.scrollTop.toString());
      };
      
      sidebar.addEventListener('scroll', handleScroll);
      return () => sidebar.removeEventListener('scroll', handleScroll);
    }
  }, []);

  // Clear scroll position when leaving dashboard
  useEffect(() => {
    if (location.pathname.startsWith('/dashboard')) {
      sessionStorage.removeItem('sidebarScrollPosition');
    }
  }, [location.pathname]);

  // Ensure shouldShowLabels is properly set based on collapsed state
  useEffect(() => {
    setShouldShowLabels(!isCollapsed || isMobileOpen);
  }, [isCollapsed, isMobileOpen]);

  // Force scroll restoration on every render for dashboard routes
  useEffect(() => {
    if (location.pathname.startsWith('/dashboard')) {
      const savedPosition = sessionStorage.getItem('sidebarScrollPosition');
      if (savedPosition) {
        setTimeout(() => {
          if (sidebarRef.current) {
            sidebarRef.current.scrollTop = parseInt(savedPosition);
          }
        }, 100);
      }
    }
  }, [location.pathname]);

  const toggleSidebar = () => {
    const newCollapsedState = !isCollapsed;
    setIsCollapsed(newCollapsedState);
    setShouldShowLabels(!newCollapsedState);
  };

  // Show labels if not collapsed OR if mobile is open
  const shouldShowLabels = !isCollapsed || isMobileOpen;

  return (
    <aside className="h-full flex flex-col bg-[rgba(15,23,42,0.95)] border-r border-purple-500/20" ref={sidebarRef}>
              {/* Header with Logo - Professional Design */}
                      {/* Header with Logo - Professional Design */}
        <div className={`sticky top-0 border-b border-white/10 backdrop-blur-md bg-[rgba(15,23,42,0.95)] ${shouldShowLabels && !isMobileOpen ? 'p-6' : 'h-0 overflow-hidden'}`}>
          <div className="flex items-center justify-between">
            {shouldShowLabels && !isMobileOpen && (
              <div className="flex items-center gap-4 flex-1">
                <Logo size="lg" showText={false} />
                <div>
                  <span className="font-bold text-xl leading-tight tracking-tight text-white">XspensesAI</span>
                </div>
              </div>
            )}
            {!shouldShowLabels && (
              <div className="flex items-center justify-center flex-1">
                <Logo size="md" showText={false} />
              </div>
            )}
            <div className="flex items-center gap-3">
              {/* Collapse Toggle Button - Only show on desktop */}
              {!isMobileOpen && (
                <button 
                  onClick={toggleSidebar}
                  className="p-2 text-white/70 hover:text-white hover:bg-white/10 rounded-xl transition-all duration-300"
                  style={{ minHeight: '44px', minWidth: '44px' }}
                >
                  {isCollapsed ? <ChevronRight size={20} /> : <ChevronLeft size={20} />}
                </button>
              )}
            </div>
          </div>
        </div>

              {/* Navigation with Independent Scrolling */}
        <div className="flex flex-col flex-1 min-h-0 overflow-hidden">
        <nav className="px-4 py-4 overflow-y-auto flex-1 sidebar-nav-scroll" style={{ maxHeight: 'calc(100vh - 200px)' }} onWheel={(e) => e.stopPropagation()}>
        {/* Main Dashboard */}
        <ul className="space-y-1 mb-4">
          <li>
            <NavLink 
              to="/dashboard" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <BarChart3 size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Main Dashboard</span>}
            </NavLink>
          </li>
        </ul>

        {/* CORE AI TOOLS */}
        {shouldShowLabels && (
          <div className="text-xs uppercase tracking-wider text-white/50 mt-4 mb-2 font-bold px-3">
            AI Workspace
          </div>
        )}
        <ul className="space-y-1 mb-4">
          <li>
            <NavLink 
              to="/dashboard/smart-import-ai" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <Upload size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Smart Import AI</span>}
            </NavLink>
          </li>
          <li>
            <NavLink 
              to="/dashboard/ai-financial-assistant" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <Bot size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">AI Chat Assistant</span>}
            </NavLink>
          </li>
          <li>
            <NavLink 
              to="/dashboard/ai-categorization" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <Brain size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Smart Categories</span>}
            </NavLink>
          </li>
          <li>
            <NavLink 
              to="/dashboard/transactions" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <FileText size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Transactions</span>}
            </NavLink>
          </li>
        </ul>

        {/* PLANNING & ANALYSIS */}
        {shouldShowLabels && (
          <div className="text-xs uppercase tracking-wider text-white/50 mt-4 mb-2 font-bold px-3">
            Planning & Analysis
          </div>
        )}
        <ul className="space-y-1 mb-4">
          <li>
            <NavLink 
              to="/dashboard/goal-concierge" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <Target size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">AI Goal Concierge</span>}
            </NavLink>
          </li>
          <li>
            <NavLink 
              to="/dashboard/spending-predictions" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <TrendingUp size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Spending Predictions</span>}
            </NavLink>
          </li>
          <li>
            <NavLink 
              to="/dashboard/debt-payoff-planner" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <CreditCard size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Debt Payoff Planner</span>}
            </NavLink>
          </li>
          <li>
            <NavLink 
              to="/dashboard/ai-financial-freedom" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <Award size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">AI Financial Freedom</span>}
            </NavLink>
          </li>
          <li>
            <NavLink 
              to="/dashboard/bill-reminders" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <Bell size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Bill Reminder System</span>}
            </NavLink>
          </li>
        </ul>

        {/* ENTERTAINMENT & WELLNESS */}
        {shouldShowLabels && (
          <div className="text-xs uppercase tracking-wider text-white/50 mt-4 mb-2 font-bold px-3">
            Entertainment & Wellness
          </div>
        )}
        <ul className="space-y-1 mb-4">
          <li>
            <NavLink 
              to="/dashboard/podcast" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <Mic size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Personal Podcast</span>}
            </NavLink>
          </li>
          <li>
            <NavLink 
              to="/dashboard/financial-therapist" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <Heart size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">AI Financial Therapist</span>}
            </NavLink>
          </li>
          <li>
            <NavLink 
              to="/dashboard/wellness-studio" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <Heart size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Wellness Studio</span>}
            </NavLink>
          </li>
          <li>
            <NavLink 
              to="/dashboard/spotify-integration" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <Music size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Spotify Integration</span>}
            </NavLink>
          </li>
        </ul>

        {/* FINANCIAL CHEERLEADERS */}
        {shouldShowLabels && (
          <div className="text-xs uppercase tracking-wider text-white/50 mt-4 mb-2 font-bold px-3">
            Financial Cheerleaders
          </div>
        )}
        <ul className="space-y-1 mb-4">
          <li>
            <NavLink 
              to="/dashboard/spark" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <Zap size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Spark</span>}
            </NavLink>
          </li>
          <li>
            <NavLink 
              to="/dashboard/wisdom" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <Brain size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Wisdom</span>}
            </NavLink>
          </li>
          <li>
            <NavLink 
              to="/dashboard/serenity" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <Heart size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Serenity</span>}
            </NavLink>
          </li>
          <li>
            <NavLink 
              to="/dashboard/fortune" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <Star size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Fortune</span>}
            </NavLink>
          </li>
          <li>
            <NavLink 
              to="/dashboard/nova" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <Sparkles size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Nova</span>}
            </NavLink>
          </li>
          <li>
            <NavLink 
              to="/dashboard/harmony" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <Music size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Harmony</span>}
            </NavLink>
          </li>
        </ul>

        {/* BUSINESS & TAX */}
        {shouldShowLabels && (
          <div className="text-xs uppercase tracking-wider text-white/50 mt-4 mb-2 font-bold px-3">
            Business & Tax
          </div>
        )}
        <ul className="space-y-1 mb-4">
          <li>
            <NavLink 
              to="/dashboard/tax-assistant" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <Calculator size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Tax Assistant</span>}
            </NavLink>
          </li>
          <li>
            <NavLink 
              to="/dashboard/business-intelligence" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <Building2 size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Business Intelligence</span>}
            </NavLink>
          </li>
          <li>
            <NavLink 
              to="/dashboard/smart-automation" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <Zap size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Smart Automation</span>}
            </NavLink>
          </li>
        </ul>

        {/* GET ROASTED */}
        {shouldShowLabels && (
          <div className="text-xs uppercase tracking-wider text-white/50 mt-4 mb-2 font-bold px-3">
            Get Roasted
          </div>
        )}
        <ul className="space-y-1 mb-4">
          <li>
            <NavLink 
              to="/dashboard/roast-master" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <Zap size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Roast Master</span>}
            </NavLink>
          </li>
          <li>
            <NavLink 
              to="/dashboard/savage-sally" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <Zap size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Savage Sally</span>}
            </NavLink>
          </li>
          <li>
            <NavLink 
              to="/dashboard/truth-bomber" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <Zap size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Truth Bomber</span>}
            </NavLink>
          </li>
          <li>
            <NavLink 
              to="/dashboard/reality-checker" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <Banknote size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Reality Checker</span>}
            </NavLink>
          </li>
          <li>
            <NavLink 
              to="/dashboard/savage-sam" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <Zap size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Savage Sam</span>}
            </NavLink>
          </li>
          <li>
            <NavLink 
              to="/dashboard/roast-queen" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <Zap size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Roast Queen</span>}
            </NavLink>
          </li>
        </ul>

        {/* TOOLS & SETTINGS */}
        {shouldShowLabels && (
          <div className="text-xs uppercase tracking-wider text-white/50 mt-4 mb-2 font-bold px-3">
            Tools & Settings
          </div>
        )}
        <ul className="space-y-1 mb-4">
          <li>
            <NavLink 
              to="/dashboard/analytics" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <BarChart3 size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Analytics</span>}
            </NavLink>
          </li>
          <li>
            <NavLink 
              to="/dashboard/settings" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <Settings size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Settings</span>}
            </NavLink>
          </li>
          <li>
            <NavLink 
              to="/dashboard/reports" 
              className={({ isActive }) => 
                `flex items-center gap-3 py-3 px-3 rounded-xl transition-all duration-200 hover:bg-white/10 active:scale-95 ${
                  isActive ? 'bg-purple-500/20 border-l-4 border-purple-400' : ''
                }`
              }
              style={{ minHeight: '48px' }}
              onClick={() => isMobileOpen && setIsMobileOpen(false)}
            >
              <FileText size={20} className="flex-shrink-0 text-white/90" />
              {shouldShowLabels && <span className="font-medium text-white/90">Reports</span>}
            </NavLink>
          </li>
        </ul>
        </nav>

        {/* Premium User Badge at the very bottom */}
        <div className="border-t border-white/10 px-4 py-4 mt-auto w-full box-border bg-[rgba(15,23,42,0.95)]">
        {shouldShowLabels && (
          <div className="p-4 bg-gradient-to-br from-purple-600 to-cyan-500 rounded-xl border border-purple-500/30 shadow-lg">
            <div className="flex items-center gap-3 mb-3">
              <div className="w-10 h-10 bg-gradient-to-br from-purple-500 to-pink-500 rounded-full flex items-center justify-center">
                <User size={20} className="text-white" />
              </div>
              <div className="flex-1">
                <div className="font-semibold text-white text-sm">{user?.name || 'John Doe'}</div>
                <div className="text-xs text-white/80">{user?.plan || 'Premium Plan'}</div>
              </div>
            </div>
            <div className="bg-white/20 text-white px-2 py-1 rounded-md text-xs font-medium backdrop-blur-sm">
              Level 8 Money Master
            </div>
          </div>
        )}
        {!shouldShowLabels && (
          <div className="flex justify-center">
            <div className="w-10 h-10 bg-gradient-to-br from-purple-500 to-pink-500 rounded-full flex items-center justify-center">
              <User size={20} className="text-white" />
            </div>
          </div>
        )}
        </div>
      </div>
    </aside>
  );
}
