import React from 'react';
import WebsiteLayout from '../components/layout/WebsiteLayout';
import { PersonalPodcastDashboard } from '../components/podcast/PersonalPodcastDashboard';
import { motion } from 'framer-motion';

export default function PersonalPodcastPage() {
  return (
    <WebsiteLayout>
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-purple-900 via-blue-900 to-pink-700 text-white py-20 px-4 text-center rounded-3xl shadow-xl mb-16">
        <motion.h1
          className="text-5xl md:text-6xl font-extrabold mb-6"
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
        >
          Get Your Own Financial Podcast <span className="bg-gradient-to-r from-orange-400 to-pink-400 bg-clip-text text-transparent">Generated by AI</span>
        </motion.h1>
        <motion.p
          className="text-xl md:text-2xl text-blue-100 mb-10 max-w-2xl mx-auto"
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.2 }}
        >
          Monthly episodes about <span className="font-bold text-white">YOUR</span> money story. Celebrate wins, understand your patterns, and get motivated—like having a personal financial coach who knows your journey.
        </motion.p>
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.4 }}
        >
          <a
            href="#podcast-demo"
            className="inline-block bg-gradient-to-r from-orange-500 to-pink-500 text-white px-10 py-5 rounded-xl font-bold text-lg shadow-lg hover:from-pink-500 hover:to-orange-500 transition-all duration-300"
          >
            Generate My First Episode Free
          </a>
        </motion.div>
      </section>

      {/* Interactive Podcast Player Demo */}
      <section id="podcast-demo" className="max-w-5xl mx-auto mb-20">
        <PersonalPodcastDashboard />
      </section>

      {/* Before/After Comparison */}
      <section className="max-w-4xl mx-auto mb-20 grid md:grid-cols-2 gap-8 items-center">
        <div className="bg-white rounded-2xl shadow-lg p-8 text-center">
          <h3 className="text-2xl font-bold text-gray-900 mb-4">Before: Boring Expense Reports</h3>
          <p className="text-gray-600 mb-4">Endless spreadsheets, confusing charts, and no motivation to improve.</p>
          <div className="bg-gray-100 rounded-lg p-4 text-gray-500 text-sm">"You spent $2,400 on groceries. Your average spending increased by 12%." <br/> <span className="italic">(Yawn...)</span></div>
        </div>
        <div className="bg-gradient-to-br from-purple-500 to-pink-500 rounded-2xl shadow-lg p-8 text-center text-white">
          <h3 className="text-2xl font-bold mb-4">After: Engaging Personal Financial Stories</h3>
          <p className="mb-4">AI-generated podcast episodes that celebrate your wins, explain your patterns, and motivate you to succeed.</p>
          <div className="bg-white/10 rounded-lg p-4 text-pink-100 text-sm">"Sarah, you crushed your grocery budget this month! Let's celebrate your progress and set a new goal for next month." <br/> <span className="italic">(Now that's motivating!)</span></div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="max-w-5xl mx-auto mb-20">
        <h2 className="text-3xl font-bold text-center mb-10 text-gray-900">How Real Users Transformed Their Finances</h2>
        <div className="grid md:grid-cols-3 gap-8">
          <div className="bg-white rounded-xl shadow-lg p-6 flex flex-col items-center text-center">
            <div className="w-14 h-14 bg-gradient-to-r from-purple-500 to-pink-500 rounded-full flex items-center justify-center mb-4 text-white text-2xl">🎧</div>
            <p className="text-gray-700 italic mb-4">"I never thought I'd look forward to my monthly expense review. The podcast makes it fun and personal!"</p>
            <div className="font-bold text-gray-900">Alex M.</div>
            <div className="text-sm text-gray-500">Freelancer</div>
          </div>
          <div className="bg-white rounded-xl shadow-lg p-6 flex flex-col items-center text-center">
            <div className="w-14 h-14 bg-gradient-to-r from-purple-500 to-pink-500 rounded-full flex items-center justify-center mb-4 text-white text-2xl">🎙️</div>
            <p className="text-gray-700 italic mb-4">"My AI podcast celebrated my first savings goal. It felt like having a coach cheering me on!"</p>
            <div className="font-bold text-gray-900">Jamie L.</div>
            <div className="text-sm text-gray-500">Designer</div>
          </div>
          <div className="bg-white rounded-xl shadow-lg p-6 flex flex-col items-center text-center">
            <div className="w-14 h-14 bg-gradient-to-r from-purple-500 to-pink-500 rounded-full flex items-center justify-center mb-4 text-white text-2xl">📈</div>
            <p className="text-gray-700 italic mb-4">"I finally understand my spending habits. The podcast makes it easy and enjoyable to improve."</p>
            <div className="font-bold text-gray-900">Morgan S.</div>
            <div className="text-sm text-gray-500">Entrepreneur</div>
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-16 bg-gradient-to-r from-purple-500 to-pink-500 rounded-2xl mt-16 text-white text-center max-w-4xl mx-auto shadow-xl">
        <motion.h2
          className="text-4xl md:text-5xl font-bold text-white mb-4"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
        >
          Ready to Hear Your Money Story?
        </motion.h2>
        <p className="text-xl text-purple-100 mb-8">
          Join thousands who turned boring expense reports into engaging, personalized podcasts.
        </p>
        <a
          href="#podcast-demo"
          className="bg-white text-purple-600 px-8 py-4 rounded-xl text-lg font-semibold hover:shadow-xl transform hover:scale-105 transition-all duration-200"
        >
          Generate My First Episode Free
        </a>
      </section>
    </WebsiteLayout>
  );
} 