/**
 * Employee Display Configuration
 * 
 * Centralized source of truth for employee visual branding, stats, and display metadata.
 * Used by hero cards, chat headers, and employee-specific UI components.
 * 
 * This config is separate from employeeChatConfig.ts (which handles chat behavior)
 * and focuses purely on visual presentation and display properties.
 */

export interface EmployeeStat {
  value: string;
  label: string;
  colorClass: string; // Tailwind text color class, e.g. 'text-cyan-400'
}

export interface EmployeeDisplayConfig {
  emoji: string;
  displayName: string; // Short name, e.g. "Prime", "Byte"
  title: string; // Full title, e.g. "Prime — AI Command Center"
  subtitle: string; // Short description
  gradient: string; // Tailwind gradient classes for buttons/accents
  accentGlow: string; // Tailwind class for radial glow behind avatar, e.g. 'bg-sky-500/10'
  accentShadow: string; // Tailwind shadow class for avatar glow, e.g. 'shadow-[0_0_40px_rgba(56,189,248,0.7)]'
  accentColor: string; // Primary accent color for borders/glow, e.g. 'sky-500'
  primaryButtonGradient: string; // Gradient for primary chat button
  primaryButtonShadow: string; // Shadow class for primary button, e.g. 'shadow-blue-900/60'
  stats?: EmployeeStat[]; // Default stats to display (optional, can be overridden)
  // Chat-specific display config
  chatTitle: string; // Short title for chat header, e.g. "Byte — Chat"
  chatSubtitle: string; // One-line role description for chat header, e.g. "Smart Import & OCR Wizard"
  chatQuickPrompts: string[]; // Array of 3-6 suggested questions for "Try asking" row
  chatAccentGlow?: string; // Optional Tailwind class for avatar/glow ring in chat header (reuses accentGlow if not provided)
}

export const EMPLOYEE_DISPLAY_CONFIG: Record<string, EmployeeDisplayConfig> = {
  'prime-boss': {
    emoji: '👑',
    displayName: 'Prime',
    title: 'Prime — AI Command Center',
    subtitle: 'Your financial CEO · Routing tasks and coordinating your AI team',
    gradient: 'from-amber-400 via-orange-500 to-pink-500',
    accentGlow: 'bg-amber-500/10',
    accentShadow: 'shadow-[0_0_40px_rgba(251,191,36,0.7)]',
    accentColor: 'amber-500',
    primaryButtonGradient: 'from-amber-400 via-orange-500 to-pink-500',
    primaryButtonShadow: 'shadow-amber-900/60',
    stats: [
      { value: '—', label: 'AI Agents', colorClass: 'text-blue-400' },
      { value: '—', label: 'Tasks Routed', colorClass: 'text-yellow-400' },
      { value: '—', label: 'Success Rate', colorClass: 'text-green-400' },
    ],
    chatTitle: 'Prime — Chat',
    chatSubtitle: 'AI Orchestrator & Financial Guide',
    chatQuickPrompts: [
      'Help me upload and process my bank statements.',
      'Explain my recent spending patterns and any trends.',
      'Review my categories and fix anything that looks wrong.',
    ],
  },
  'byte-docs': {
    emoji: '📄',
    displayName: 'Byte',
    title: 'Byte — Smart Import AI',
    subtitle: 'Smart Import specialist · Handles documents, OCR and clean transaction data',
    gradient: 'from-sky-400 via-cyan-400 to-emerald-400',
    accentGlow: 'bg-sky-500/10',
    accentShadow: 'shadow-[0_0_40px_rgba(56,189,248,0.7)]',
    accentColor: 'sky-500',
    primaryButtonGradient: 'from-sky-400 via-blue-500 to-indigo-500',
    primaryButtonShadow: 'shadow-blue-900/60',
    stats: [
      { value: '99.7%', label: 'Accuracy', colorClass: 'text-cyan-400' },
      { value: '2.3s', label: 'Avg Speed', colorClass: 'text-green-400' },
      { value: '24/7', label: 'Available', colorClass: 'text-purple-400' },
    ],
    chatTitle: 'Byte — Chat',
    chatSubtitle: 'Smart Import & OCR Wizard',
    chatQuickPrompts: [
      'Scan my latest receipts and show me today\'s total spending.',
      'Import my last bank statement and summarize my top merchants.',
      'Flag any duplicate transactions from my recent uploads.',
      'What file formats can I upload for processing?',
    ],
  },
  'tag-ai': {
    emoji: '🏷️',
    displayName: 'Tag',
    title: 'Tag — Smart Categories AI',
    subtitle: 'Intelligent categorization · Auto-organize your transactions',
    gradient: 'from-yellow-300 via-amber-400 to-orange-500',
    accentGlow: 'bg-teal-500/10',
    accentShadow: 'shadow-[0_0_40px_rgba(20,184,166,0.7)]',
    accentColor: 'teal-500',
    primaryButtonGradient: 'from-teal-400 via-emerald-500 to-green-500',
    primaryButtonShadow: 'shadow-teal-900/60',
    stats: [
      { value: '1,247', label: 'Items Tagged', colorClass: 'text-cyan-400' },
      { value: '98.5%', label: 'Accuracy', colorClass: 'text-green-400' },
      { value: '45', label: 'Categories', colorClass: 'text-purple-400' },
    ],
    chatTitle: 'Tag — Chat',
    chatSubtitle: 'Smart Categories & Rules Engine',
    chatQuickPrompts: [
      'Show me all uncategorized transactions from the last 30 days.',
      'Fix any obvious category mistakes from restaurants vs groceries.',
      'Create a rule so Uber rides always go into \'Transportation\'.',
      'Go through my transactions and clean up the categories.',
    ],
  },
  'finley-forecasts': {
    emoji: '💰',
    displayName: 'Finley',
    title: 'Finley — AI Financial Assistant',
    subtitle: 'Personalized financial brain · Ask anything about your finances',
    gradient: 'from-yellow-400 via-orange-500 to-amber-500',
    accentGlow: 'bg-orange-500/10',
    accentShadow: 'shadow-[0_0_40px_rgba(249,115,22,0.7)]',
    accentColor: 'orange-500',
    primaryButtonGradient: 'from-orange-400 via-amber-500 to-yellow-500',
    primaryButtonShadow: 'shadow-orange-900/60',
    stats: [
      { value: '234', label: 'Questions', colorClass: 'text-blue-400' },
      { value: '92%', label: 'Satisfaction', colorClass: 'text-green-400' },
      { value: '1.2s', label: 'Avg Response', colorClass: 'text-purple-400' },
    ],
    chatTitle: 'Finley — Chat',
    chatSubtitle: 'Financial Forecasting',
    chatQuickPrompts: [
      'How long will it take to pay off my credit card debt?',
      'If I save $500 per month, how much will I have in 2 years?',
      'What\'s my projected cash flow for the next 6 months?',
      'Help me create a savings forecast for my vacation goal.',
    ],
  },
  'goalie-goals': {
    emoji: '🥅',
    displayName: 'Goalie',
    title: 'Goalie — AI Goal Concierge',
    subtitle: 'Goal tracking specialist · Turn dreams into achievable milestones',
    gradient: 'from-amber-400 via-yellow-500 to-orange-500',
    accentGlow: 'bg-amber-500/10',
    accentShadow: 'shadow-[0_0_40px_rgba(245,158,11,0.7)]',
    accentColor: 'amber-500',
    primaryButtonGradient: 'from-amber-400 via-yellow-500 to-orange-500',
    primaryButtonShadow: 'shadow-amber-900/60',
    stats: [
      { value: '8', label: 'Active Goals', colorClass: 'text-blue-400' },
      { value: '87%', label: 'On Track', colorClass: 'text-green-400' },
      { value: '23', label: 'Milestones Hit', colorClass: 'text-purple-400' },
    ],
    chatTitle: 'Goalie — Chat',
    chatSubtitle: 'Goal Progress & Achievement',
    chatQuickPrompts: [
      'Show me my current financial goals and progress.',
      'Help me create a new savings goal for a down payment.',
      'What milestones should I hit next to stay on track?',
      'Celebrate my recent goal achievements!',
    ],
  },
  'crystal-analytics': {
    emoji: '📈',
    displayName: 'Crystal',
    title: 'Analytics — AI Insights Engine',
    subtitle: 'Deep financial analysis · Uncover patterns and opportunities',
    gradient: 'from-purple-400 via-indigo-400 to-sky-400',
    accentGlow: 'bg-indigo-500/10',
    accentShadow: 'shadow-[0_0_40px_rgba(99,102,241,0.7)]',
    accentColor: 'indigo-500',
    primaryButtonGradient: 'from-purple-400 via-indigo-400 to-sky-400',
    primaryButtonShadow: 'shadow-indigo-900/60',
    stats: [
      { value: '156', label: 'Reports Generated', colorClass: 'text-blue-400' },
      { value: '2,340', label: 'Insights Found', colorClass: 'text-green-400' },
      { value: '50K+', label: 'Data Points', colorClass: 'text-purple-400' },
    ],
    chatTitle: 'Crystal — Chat',
    chatSubtitle: 'Analytics & Insights',
    chatQuickPrompts: [
      'Give me a monthly summary of my expenses for the last 3 months.',
      'Show me my top 10 merchants this year.',
      'Highlight any unusual or suspicious spending.',
      'What are my spending trends over the last 6 months?',
    ],
  },
  'debt-payoff-planner': {
    emoji: '💳',
    displayName: 'Debt',
    title: 'Debt — Payoff Planner',
    subtitle: 'Debt elimination specialist · Optimize your path to freedom',
    gradient: 'from-rose-400 via-pink-500 to-red-500',
    accentGlow: 'bg-rose-500/10',
    accentShadow: 'shadow-[0_0_40px_rgba(244,63,94,0.7)]',
    accentColor: 'rose-500',
    primaryButtonGradient: 'from-rose-400 via-pink-500 to-red-500',
    primaryButtonShadow: 'shadow-rose-900/60',
    stats: [
      { value: '$12,450', label: 'Total Debt', colorClass: 'text-rose-400' },
      { value: '$1,247', label: 'Interest Saved', colorClass: 'text-green-400' },
      { value: '18mo', label: 'To Payoff', colorClass: 'text-blue-400' },
    ],
    chatTitle: 'Debt — Chat',
    chatSubtitle: 'Debt Payoff & Strategy',
    chatQuickPrompts: [
      'Show me my current debt payoff plan and progress.',
      'Help me optimize my payment strategy to save on interest.',
      'Compare avalanche vs snowball payoff methods for my debts.',
      'What\'s my estimated payoff date if I increase payments?',
    ],
  },
  'crystal-spending': {
    emoji: '🔮',
    displayName: 'Crystal',
    title: 'Crystal — Spending Predictions AI',
    subtitle: 'Future spending oracle · See what\'s coming before it happens',
    gradient: 'from-fuchsia-400 via-purple-400 to-pink-400',
    accentGlow: 'bg-fuchsia-500/10',
    accentShadow: 'shadow-[0_0_40px_rgba(217,70,239,0.7)]',
    accentColor: 'fuchsia-500',
    primaryButtonGradient: 'from-fuchsia-400 via-purple-400 to-pink-400',
    primaryButtonShadow: 'shadow-fuchsia-900/60',
    stats: [
      { value: '94.2%', label: 'Prediction Accuracy', colorClass: 'text-cyan-400' },
      { value: '$3,420', label: 'Forecasted Spend', colorClass: 'text-green-400' },
      { value: '3', label: 'Alerts Active', colorClass: 'text-amber-400' },
    ],
    chatTitle: 'Crystal — Chat',
    chatSubtitle: 'Spending Predictions & Forecasting',
    chatQuickPrompts: [
      'What will my spending look like next month?',
      'Show me unusual spending patterns I should watch for.',
      'Predict my spending by category for the next quarter.',
      'Alert me if my spending trends are concerning.',
    ],
  },
  'dash-analytics': {
    emoji: '📊',
    displayName: 'Dash',
    title: 'Dash — Business Intelligence',
    subtitle: 'Strategic insights engine · Transform data into business decisions',
    gradient: 'from-indigo-400 via-blue-400 to-purple-400',
    accentGlow: 'bg-indigo-500/10',
    accentShadow: 'shadow-[0_0_40px_rgba(99,102,241,0.7)]',
    accentColor: 'indigo-500',
    primaryButtonGradient: 'from-indigo-400 via-blue-400 to-purple-400',
    primaryButtonShadow: 'shadow-indigo-900/60',
    stats: [
      { value: '48', label: 'Reports Generated', colorClass: 'text-indigo-400' },
      { value: '156', label: 'Insights Found', colorClass: 'text-green-400' },
      { value: '12', label: 'KPIs Tracked', colorClass: 'text-purple-400' },
    ],
    chatTitle: 'Dash — Chat',
    chatSubtitle: 'Business Intelligence & Analytics',
    chatQuickPrompts: [
      'Generate a business intelligence report for this month.',
      'What are the key insights from my financial data?',
      'Show me KPIs and trends for my business.',
      'Compare this quarter\'s performance to last quarter.',
    ],
  },
  'smart-automation': {
    emoji: '⚙️',
    displayName: 'Automation',
    title: 'Smart Automation — Rule Engine',
    subtitle: 'Intelligent automation · Set rules and let AI handle the rest',
    gradient: 'from-violet-400 via-purple-400 to-fuchsia-400',
    accentGlow: 'bg-violet-500/10',
    accentShadow: 'shadow-[0_0_40px_rgba(139,92,246,0.7)]',
    accentColor: 'violet-500',
    primaryButtonGradient: 'from-violet-400 via-purple-400 to-fuchsia-400',
    primaryButtonShadow: 'shadow-violet-900/60',
    stats: [
      { value: '15', label: 'Active Rules', colorClass: 'text-blue-400' },
      { value: '342', label: 'Actions This Month', colorClass: 'text-green-400' },
      { value: '8.5hrs', label: 'Time Saved', colorClass: 'text-purple-400' },
    ],
    chatTitle: 'Automation — Chat',
    chatSubtitle: 'Smart Rules & Workflows',
    chatQuickPrompts: [
      'Show me my active automation rules.',
      'Create a new rule to automatically categorize transactions.',
      'What actions have my automations taken this month?',
      'Help me set up a bill payment reminder automation.',
    ],
  },
  'bank-accounts': {
    emoji: '🏦',
    displayName: 'Bank',
    title: 'Bank Accounts — Connected Hub',
    subtitle: 'Secure bank connections · Real-time balance tracking',
    gradient: 'from-emerald-400 via-green-400 to-teal-400',
    accentGlow: 'bg-emerald-500/10',
    accentShadow: 'shadow-[0_0_40px_rgba(16,185,129,0.7)]',
    accentColor: 'emerald-500',
    primaryButtonGradient: 'from-emerald-400 via-green-400 to-teal-400',
    primaryButtonShadow: 'shadow-emerald-900/60',
    stats: [
      { value: '5', label: 'Connected Accounts', colorClass: 'text-blue-400' },
      { value: '$24,580', label: 'Total Balance', colorClass: 'text-green-400' },
      { value: '2min', label: 'Last Synced', colorClass: 'text-purple-400' },
    ],
    chatTitle: 'Bank — Chat',
    chatSubtitle: 'Account Management & Sync',
    chatQuickPrompts: [
      'Show me all my connected bank accounts.',
      'Sync my latest transactions from all accounts.',
      'What\'s my total balance across all accounts?',
      'Help me connect a new bank account.',
    ],
  },
  'bill-reminders': {
    emoji: '🔔',
    displayName: 'Bills',
    title: 'Bill Reminders — Never Miss a Payment',
    subtitle: 'Smart bill tracking · Automated reminders and payment scheduling',
    gradient: 'from-sky-400 via-blue-400 to-cyan-400',
    accentGlow: 'bg-sky-500/10',
    accentShadow: 'shadow-[0_0_40px_rgba(14,165,233,0.7)]',
    accentColor: 'sky-500',
    primaryButtonGradient: 'from-sky-400 via-blue-400 to-cyan-400',
    primaryButtonShadow: 'shadow-sky-900/60',
    stats: [
      { value: '8', label: 'Upcoming Bills', colorClass: 'text-blue-400' },
      { value: '98%', label: 'Paid On Time', colorClass: 'text-green-400' },
      { value: '$2,340', label: 'Due This Month', colorClass: 'text-amber-400' },
    ],
    chatTitle: 'Bills — Chat',
    chatSubtitle: 'Bill Tracking & Reminders',
    chatQuickPrompts: [
      'Show me my upcoming bills for this month.',
      'What bills are due in the next week?',
      'Help me set up automatic bill reminders.',
      'Track my bill payment history.',
    ],
  },
  'wellness-studio': {
    emoji: '🧘',
    displayName: 'Wellness',
    title: 'Wellness — Financial Self-Care',
    subtitle: 'Balance your financial health with mindful practices',
    gradient: 'from-teal-400 via-emerald-400 to-green-400',
    accentGlow: 'bg-teal-500/10',
    accentShadow: 'shadow-[0_0_40px_rgba(20,184,166,0.7)]',
    accentColor: 'teal-500',
    primaryButtonGradient: 'from-teal-400 via-emerald-400 to-green-400',
    primaryButtonShadow: 'shadow-teal-900/60',
    stats: [
      { value: '85', label: 'Wellness Score', colorClass: 'text-teal-400' },
      { value: '12', label: 'Day Streak', colorClass: 'text-green-400' },
      { value: '34', label: 'Activities Done', colorClass: 'text-purple-400' },
    ],
    chatTitle: 'Wellness — Chat',
    chatSubtitle: 'Financial Wellness & Self-Care',
    chatQuickPrompts: [
      'How can I improve my financial wellness score?',
      'Show me my wellness activity streak.',
      'What mindfulness practices can help with money stress?',
      'Track my financial wellness progress.',
    ],
  },
  'financial-therapist': {
    emoji: '💚',
    displayName: 'Therapist',
    title: 'Therapist — Money Wellness',
    subtitle: 'Understand your relationship with money and reduce stress',
    gradient: 'from-emerald-400 via-green-400 to-teal-400',
    accentGlow: 'bg-emerald-500/10',
    accentShadow: 'shadow-[0_0_40px_rgba(16,185,129,0.7)]',
    accentColor: 'emerald-500',
    primaryButtonGradient: 'from-emerald-400 via-green-400 to-teal-400',
    primaryButtonShadow: 'shadow-emerald-900/60',
    stats: [
      { value: '15', label: 'Sessions Completed', colorClass: 'text-emerald-400' },
      { value: '67%', label: 'Stress Reduced', colorClass: 'text-green-400' },
      { value: '↑', label: 'Mood Trending Up', colorClass: 'text-blue-400' },
    ],
    chatTitle: 'Therapist — Chat',
    chatSubtitle: 'Financial Therapy & Support',
    chatQuickPrompts: [
      'Help me understand my relationship with money.',
      'I\'m feeling stressed about my finances. Can you help?',
      'What are healthy financial habits I should practice?',
      'Track my financial wellness journey.',
    ],
  },
  'financial-story': {
    emoji: '📖',
    displayName: 'Story',
    title: 'Financial Story — Your Money Journey',
    subtitle: 'Turn your financial data into meaningful narratives',
    gradient: 'from-amber-400 via-yellow-400 to-orange-400',
    accentGlow: 'bg-amber-500/10',
    accentShadow: 'shadow-[0_0_40px_rgba(245,158,11,0.7)]',
    accentColor: 'amber-500',
    primaryButtonGradient: 'from-amber-400 via-yellow-400 to-orange-400',
    primaryButtonShadow: 'shadow-amber-900/60',
    stats: [
      { value: '8', label: 'Stories Created', colorClass: 'text-amber-400' },
      { value: '24', label: 'Insights Captured', colorClass: 'text-green-400' },
      { value: '156', label: 'Milestones', colorClass: 'text-blue-400' },
    ],
    chatTitle: 'Story — Chat',
    chatSubtitle: 'Financial Storytelling & Narratives',
    chatQuickPrompts: [
      'Create a story about my financial journey this year.',
      'Show me the milestones I\'ve achieved.',
      'What insights can you share about my money story?',
      'Help me visualize my financial progress over time.',
    ],
  },
  'personal-podcast': {
    emoji: '🎙️',
    displayName: 'Podcast',
    title: 'Podcast — AI Audio Creator',
    subtitle: 'Transform your finances into engaging audio content',
    gradient: 'from-red-400 via-rose-400 to-pink-400',
    accentGlow: 'bg-red-500/10',
    accentShadow: 'shadow-[0_0_40px_rgba(239,68,68,0.7)]',
    accentColor: 'red-500',
    primaryButtonGradient: 'from-red-400 via-rose-400 to-pink-400',
    primaryButtonShadow: 'shadow-red-900/60',
    stats: [
      { value: '12', label: 'Episodes Created', colorClass: 'text-red-400' },
      { value: '3.5hrs', label: 'Total Duration', colorClass: 'text-green-400' },
      { value: '847', label: 'Total Listens', colorClass: 'text-blue-400' },
    ],
    chatTitle: 'Podcast — Chat',
    chatSubtitle: 'Audio Content Creation',
    chatQuickPrompts: [
      'Create a new podcast episode about my finances.',
      'Show me my podcast library and episodes.',
      'What topics should I cover in my next episode?',
      'Help me share my podcast episodes.',
    ],
  },
  'spotify-integration': {
    emoji: '🎵',
    displayName: 'Spotify',
    title: 'Spotify — Music Integration',
    subtitle: 'Connect your music to your financial journey',
    gradient: 'from-green-400 via-emerald-400 to-teal-400',
    accentGlow: 'bg-green-500/10',
    accentShadow: 'shadow-[0_0_40px_rgba(34,197,94,0.7)]',
    accentColor: 'green-500',
    primaryButtonGradient: 'from-green-400 via-emerald-400 to-teal-400',
    primaryButtonShadow: 'shadow-green-900/60',
    stats: [
      { value: 'Connected', label: 'Status', colorClass: 'text-green-400' },
      { value: '5', label: 'Playlists Created', colorClass: 'text-blue-400' },
      { value: '48hrs', label: 'Listening Time', colorClass: 'text-purple-400' },
    ],
    chatTitle: 'Spotify — Chat',
    chatSubtitle: 'Music & Finance Integration',
    chatQuickPrompts: [
      'Connect my Spotify account.',
      'Create a playlist based on my financial mood.',
      'Show me my financial music playlists.',
      'What music matches my current financial situation?',
    ],
  },
  'liberty-financial-freedom': {
    emoji: '🕊️',
    displayName: 'Liberty',
    title: 'Liberty — Financial Freedom',
    subtitle: 'Financial freedom specialist · Break free from debt and achieve independence',
    gradient: 'from-red-400 via-rose-400 to-pink-400',
    accentGlow: 'bg-red-500/10',
    accentShadow: 'shadow-[0_0_40px_rgba(239,68,68,0.7)]',
    accentColor: 'red-500',
    primaryButtonGradient: 'from-red-400 via-rose-400 to-pink-400',
    primaryButtonShadow: 'shadow-red-900/60',
    stats: [
      { value: '87%', label: 'Stress Reduction', colorClass: 'text-red-400' },
      { value: '$1,247', label: 'Interest Saved', colorClass: 'text-green-400' },
      { value: '18mo', label: 'To Freedom', colorClass: 'text-blue-400' },
    ],
    chatTitle: 'Liberty — Chat',
    chatSubtitle: 'Financial Freedom & Independence',
    chatQuickPrompts: [
      'Show me my path to financial freedom.',
      'Help me break free from debt.',
      'What strategies can help me achieve financial independence?',
      'Track my progress toward financial freedom.',
    ],
  },
  'transactions': {
    emoji: '🧾',
    displayName: 'Transactions',
    title: 'Transactions — Financial Hub',
    subtitle: 'Complete transaction history · Track every dollar in and out',
    gradient: 'from-slate-400 via-gray-400 to-zinc-400',
    accentGlow: 'bg-slate-500/10',
    accentShadow: 'shadow-[0_0_40px_rgba(100,116,139,0.7)]',
    accentColor: 'slate-500',
    primaryButtonGradient: 'from-slate-400 via-gray-400 to-zinc-400',
    primaryButtonShadow: 'shadow-slate-900/60',
    stats: [
      { value: '1,847', label: 'Total Transactions', colorClass: 'text-blue-400' },
      { value: '$12,450', label: 'This Month', colorClass: 'text-green-400' },
      { value: '98.5%', label: 'Categorized', colorClass: 'text-purple-400' },
    ],
    chatTitle: 'Transactions — Chat',
    chatSubtitle: 'Transaction History & Management',
    chatQuickPrompts: [
      'Show me my recent transactions.',
      'What are my top spending categories this month?',
      'Help me find a specific transaction.',
      'Export my transaction history.',
    ],
  },
};

/**
 * Get display config for an employee slug
 * Returns a default config if slug not found
 */
export function getEmployeeDisplayConfig(slug: string): EmployeeDisplayConfig {
  return EMPLOYEE_DISPLAY_CONFIG[slug] || {
    emoji: '✨',
    displayName: 'AI Assistant',
    title: 'AI Assistant',
    subtitle: 'Your AI assistant',
    gradient: 'from-slate-400 to-slate-600',
    accentGlow: 'bg-slate-500/10',
    accentShadow: 'shadow-[0_0_40px_rgba(148,163,184,0.7)]',
    accentColor: 'slate-500',
    primaryButtonGradient: 'from-slate-400 to-slate-600',
    primaryButtonShadow: 'shadow-slate-900/60',
    chatTitle: 'AI Assistant — Chat',
    chatSubtitle: 'Your AI assistant',
    chatQuickPrompts: [
      'How can you help me?',
      'What can you do?',
    ],
  };
}

