/**
 * AssistantWorkspacePanel Component
 * 
 * Left sidebar panel for AI Chat Assistant workspace showing recent questions, saved explanations, and planning sessions
 * MultipurposeThemes-style list layout
 * 
 * TODO: Wire this to real assistant data from Supabase
 * - Recent questions: Fetch from conversations table filtered by user_id and employee_slug='finley-ai'
 * - Saved explanations: User-saved explanations/bookmarks from a future bookmarks table
 * - Spending pattern alerts: Alerts generated by Crystal or other employees
 * - Open planning sessions: Active planning conversations or saved planning contexts
 */

import React from 'react';

interface TaskItem {
  id: string;
  title: string;
  subtitle?: string;
  timestamp?: string;
  icon?: string;
}

// Static placeholder data - TODO: Replace with real data from Supabase
const mockTasks: TaskItem[] = [
  {
    id: '1',
    title: 'Recent questions',
    subtitle: '5 conversations',
    timestamp: '3m ago',
    icon: '💬',
  },
  {
    id: '2',
    title: 'Saved explanations',
    subtitle: '3 bookmarked insights',
    timestamp: '1h ago',
    icon: '⭐',
  },
  {
    id: '3',
    title: 'Spending pattern alerts',
    subtitle: '2 new insights',
    timestamp: '2h ago',
    icon: '🔔',
  },
  {
    id: '4',
    title: 'Open planning sessions',
    subtitle: 'Budget planning active',
    timestamp: '1d ago',
    icon: '📋',
  },
];

export function AssistantWorkspacePanel() {
  return (
    <div className="bg-slate-900/70 border border-slate-800/80 rounded-2xl shadow-[0_18px_45px_rgba(0,0,0,0.45)] backdrop-blur p-4 sm:p-5 lg:p-6">
      <h3 className="text-xs font-semibold tracking-wide text-slate-300 uppercase mb-3">
        Assistant Workspace
      </h3>
      
      <div className="h-px bg-slate-800/70 mb-4"></div>
      
      {/* TODO: Replace this static list with real assistant data from Supabase */}
      <div className="space-y-2">
        {mockTasks.map((task) => (
          <button
            key={task.id}
            className="w-full text-left rounded-xl px-3 py-2.5 bg-slate-900/60 text-slate-300 hover:bg-slate-800/70 hover:border hover:border-sky-500/40 transition-all duration-200 group"
          >
            <div className="flex items-start gap-3">
              {/* Avatar circle */}
              <div className="w-8 h-8 rounded-full bg-gradient-to-br from-blue-500/20 to-purple-500/20 flex items-center justify-center text-sm flex-shrink-0 group-hover:scale-110 transition-transform">
                {task.icon || '💬'}
              </div>
              
              {/* Content */}
              <div className="flex-1 min-w-0">
                <h4 className="text-xs sm:text-sm font-medium text-slate-200 truncate mb-0.5">
                  {task.title}
                </h4>
                {task.subtitle && (
                  <p className="text-xs text-slate-400 truncate mb-1">
                    {task.subtitle}
                  </p>
                )}
                {task.timestamp && (
                  <p className="text-xs text-slate-500">
                    {task.timestamp}
                  </p>
                )}
              </div>
            </div>
          </button>
        ))}
      </div>
    </div>
  );
}













