// FINAL: Do not edit this file unless you are Darrell Warner or have explicit permission.
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { 
  Upload, Bot, Headphones, Music, Play, Pause, SkipBack, SkipForward, 
  Volume2, VolumeX, Share2, Heart, Star, ChevronLeft, ChevronRight, 
  MessageCircle, AlertTriangle, TrendingUp, Sparkles, X, Plus, Target, 
  Camera, CheckCircle, ArrowLeft, Settings, BarChart3, 
  Briefcase, Zap, Cog, Shield, Bell, User, Crown,
  LayoutDashboard, FileText, Brain, BookOpen, LineChart,
  FileText as DocumentIcon, Lightbulb, Calendar, TrendingDown,
  Activity, BookOpen as EducationIcon, Calculator, PieChart, Mic
} from 'lucide-react';

import { useNotificationSpacing } from '../hooks/useNotificationSpacing';

const XspensesProDashboard = () => {
  console.log('Dashboard component rendered at:', new Date().toISOString());
  const [currentPage, setCurrentPage] = useState('dashboard');
  const [dragOver, setDragOver] = useState(false);
  const [spotifyConnected, setSpotifyConnected] = useState(false);
  const [isMobileOpen, setIsMobileOpen] = useState(false);
  const { hasNotifications } = useNotificationSpacing();

  const [alerts, setAlerts] = useState([
    { id: 1, message: '🚨 Car payment due in 2 days!', type: 'warning', dismissed: true },
    { id: 2, message: '💰 You saved $350 this month!', type: 'success', dismissed: true }
  ]);
  const [showFab, setShowFab] = useState(false);
  const [showChatbot, setShowChatbot] = useState(false);
  const [chatMessages, setChatMessages] = useState([
    { id: 1, message: 'Hello! I\'m your AI financial assistant. How can I help you today?', type: 'ai' },
    { id: 2, message: 'I need help with my budget', type: 'user' },
    { id: 3, message: 'I\'d be happy to help! Let\'s start by reviewing your spending patterns.', type: 'ai' }
  ]);
  const [newMessage, setNewMessage] = useState('');
  const [showPremiumModal, setShowPremiumModal] = useState(false);

  const handleDragOver = (e) => {
    e.preventDefault();
    setDragOver(true);
  };

  const handleDragLeave = (e) => {
    e.preventDefault();
    setDragOver(false);
  };

  const handleDrop = (e) => {
    e.preventDefault();
    setDragOver(false);
    // Handle file drop logic
  };

  const dismissAlert = (alertId) => {
    setAlerts(alerts.map(alert => 
      alert.id === alertId ? { ...alert, dismissed: true } : alert
    ));
  };

  // New FAB handlers
  const toggleFab = () => {
    setShowFab(!showFab);
  };

  const onUploadDocument = () => {
    console.log('Upload Document clicked');
    setShowFab(false);
  };

  const onScanReceipt = () => {
    console.log('Scan Receipt clicked');
    setShowFab(false);
  };

  const onSetGoal = () => {
    console.log('Set Goal clicked');
    setShowFab(false);
  };

  const onAskAI = () => {
    console.log('Ask AI clicked');
    setShowFab(false);
  };

  const toggleChatbot = () => {
    setShowChatbot(!showChatbot);
  };

  const sendMessage = () => {
    if (newMessage.trim()) {
      setChatMessages([...chatMessages, { id: Date.now(), message: newMessage, type: 'user' }]);
      setNewMessage('');
    }
  };

  const handleKeyPress = (e) => {
    if (e.key === 'Enter') {
      sendMessage();
    }
  };

  const handleClickOutside = (e) => {
    if (showChatbot && !e.target.closest('.chatbot-container')) {
      setShowChatbot(false);
    }
  };

  useEffect(() => {
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, [showChatbot]);

  const PremiumModal = () => (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg p-6 max-w-md mx-4">
        <h3 className="text-lg font-semibold mb-4">Upgrade to Premium</h3>
        <p className="text-gray-600 mb-4">Unlock advanced features and unlimited AI assistance.</p>
        <div className="flex gap-2">
          <button className="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">
            Upgrade Now
          </button>
          <button 
            onClick={() => setShowPremiumModal(false)}
            className="bg-gray-200 text-gray-800 px-4 py-2 rounded hover:bg-gray-300"
          >
            Maybe Later
          </button>
        </div>
      </div>
    </div>
  );

  return (
    <div className="h-full flex flex-col" style={{ minHeight: '100vh' }}>
      {/* Header */}
      <header className="bg-black/20 backdrop-blur-sm border-b border-white/10 p-6 flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold text-white mb-2">FinTech Entertainment Platform</h2>
          <p className="text-white/70">Welcome back, John! Here's your financial overview.</p>
        </div>
        <div className="flex items-center gap-4">
          <button className="p-2 text-white/60 hover:text-white hover:bg-white/10 rounded-lg transition-colors">
            <Bell size={20} />
          </button>
          <button className="p-2 text-white/60 hover:text-white hover:bg-white/10 rounded-lg transition-colors">
            <Settings size={20} />
          </button>
        </div>
      </header>

      {/* Scrollable Content Area */}
      <main className="flex-1 overflow-y-auto p-6 lg:p-8">
        <div className="max-w-[1600px] mx-auto px-4">
          <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-8 mt-6">
            
            {/* Smart Import AI */}
            <Link to="/dashboard/smart-import-ai" className="group w-full">
              <div className="w-full min-h-[320px] p-6 rounded-2xl bg-gradient-to-r from-blue-600 to-indigo-700 shadow-lg flex flex-col transform transition-all duration-300 hover:scale-105 hover:shadow-xl group-hover:shadow-blue-500/25">
                <div className="w-14 h-14 bg-white/20 rounded-full flex items-center justify-center mb-4">
                  <Upload size={24} className="text-white" />
                </div>
                <h3 className="text-lg font-semibold text-white mb-3">Smart Import AI</h3>
                <p className="text-white/90 text-sm mb-4 flex-grow leading-relaxed">Instantly upload or scan any bank statement, bill, or receipt—PDF, photo, CSV, Excel, or even handwritten.</p>
                <button className="w-full bg-white/20 hover:bg-white/30 text-white font-medium py-2.5 rounded-lg transition-all duration-200 transform group-hover:scale-105 text-sm">
                  Upload or Scan Now
                </button>
              </div>
            </Link>

            {/* AI Financial Assistant */}
            <Link to="/dashboard/ai-financial-assistant" className="group w-full">
              <div className="w-full min-h-[320px] p-6 rounded-2xl bg-gradient-to-r from-purple-600 to-pink-600 shadow-lg flex flex-col transform transition-all duration-300 hover:scale-105 hover:shadow-xl group-hover:shadow-purple-500/25">
                <div className="w-14 h-14 bg-white/20 rounded-full flex items-center justify-center mb-4">
                  <Bot size={24} className="text-white" />
                </div>
                <h3 className="text-lg font-semibold text-white mb-3">AI Financial Assistant</h3>
                <p className="text-white/90 text-sm mb-4 flex-grow leading-relaxed">Automatic expense tracking, spending insights, and real-time alerts—no spreadsheets required.</p>
                <button className="w-full bg-white/20 hover:bg-white/30 text-white font-medium py-2.5 rounded-lg transition-all duration-200 transform group-hover:scale-105 text-sm">
                  View Insights
                </button>
              </div>
            </Link>

            {/* AI Financial Therapist */}
            <Link to="/dashboard/financial-therapist" className="group w-full">
              <div className="w-full min-h-[320px] p-6 rounded-2xl bg-gradient-to-r from-pink-600 to-rose-600 shadow-lg flex flex-col transform transition-all duration-300 hover:scale-105 hover:shadow-xl group-hover:shadow-pink-500/25">
                <div className="w-14 h-14 bg-white/20 rounded-full flex items-center justify-center mb-4">
                  <Heart size={24} className="text-white" />
                </div>
                <h3 className="text-lg font-semibold text-white mb-3">AI Financial Therapist</h3>
                <p className="text-white/90 text-sm mb-4 flex-grow leading-relaxed">Heal your relationship with money through positive reinforcement and AI-powered encouragement.</p>
                <button className="w-full bg-white/20 hover:bg-white/30 text-white font-medium py-2.5 rounded-lg transition-all duration-200 transform group-hover:scale-105 text-sm">
                  Start Therapy
                </button>
              </div>
            </Link>

          </div>
        </div>
      </main>

      {/* Floating Action Button */}
      {showFab && (
        <div className="fixed bottom-6 right-6 z-40">
          <div className="bg-white rounded-full shadow-lg p-4 space-y-2">
            <button
              onClick={onUploadDocument}
              className="flex items-center gap-2 text-sm text-gray-700 hover:text-blue-600"
            >
              <Upload size={16} />
              Upload Document
            </button>
            <button
              onClick={onScanReceipt}
              className="flex items-center gap-2 text-sm text-gray-700 hover:text-blue-600"
            >
              <Camera size={16} />
              Scan Receipt
            </button>
            <button
              onClick={onSetGoal}
              className="flex items-center gap-2 text-sm text-gray-700 hover:text-blue-600"
            >
              <Target size={16} />
              Set Goal
            </button>
            <button
              onClick={onAskAI}
              className="flex items-center gap-2 text-sm text-gray-700 hover:text-blue-600"
            >
              <Bot size={16} />
              Ask AI
            </button>
          </div>
        </div>
      )}

      {/* FAB Toggle Button */}
      <button
        onClick={toggleFab}
        className="fixed bottom-6 right-6 z-30 bg-blue-600 text-white rounded-full p-4 shadow-lg hover:bg-blue-700 transition-colors"
      >
        <Plus size={24} />
      </button>

      {/* AI Chatbot */}
      {showChatbot && (
        <div className="fixed bottom-6 left-6 z-40 chatbot-container">
          <div className="bg-white rounded-lg shadow-xl w-80 max-h-96 overflow-hidden">
            <div className="bg-gradient-to-r from-blue-600 to-purple-600 p-4 text-white">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Bot size={20} />
                  <span className="font-semibold">AI Assistant</span>
                </div>
                <button
                  onClick={toggleChatbot}
                  className="text-white/70 hover:text-white"
                >
                  <X size={20} />
                </button>
              </div>
            </div>
            <div className="p-4 h-64 overflow-y-auto">
              {chatMessages.map((msg) => (
                <div
                  key={msg.id}
                  className={`mb-3 ${
                    msg.type === 'user' ? 'text-right' : 'text-left'
                  }`}
                >
                  <div
                    className={`inline-block p-3 rounded-lg max-w-xs ${
                      msg.type === 'user'
                        ? 'bg-blue-600 text-white'
                        : 'bg-gray-200 text-gray-800'
                    }`}
                  >
                    {msg.message}
                  </div>
                </div>
              ))}
            </div>
            <div className="p-4 border-t">
              <div className="flex gap-2">
                <input
                  type="text"
                  value={newMessage}
                  onChange={(e) => setNewMessage(e.target.value)}
                  onKeyPress={handleKeyPress}
                  placeholder="Ask me anything..."
                  className="flex-1 px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
                <button
                  onClick={sendMessage}
                  className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
                >
                  Send
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Chatbot Toggle Button */}
      <button
        onClick={toggleChatbot}
        className="fixed bottom-6 left-6 z-30 bg-purple-600 text-white rounded-full p-4 shadow-lg hover:bg-purple-700 transition-colors"
      >
        <MessageCircle size={24} />
      </button>

      {/* Premium Modal */}
      {showPremiumModal && <PremiumModal />}
    </div>
  );
};

export default XspensesProDashboard; 
